### ISSUE TITLE
[建议] 重新添加“你知道吗”

### ISSUE THREAD

**Issue by Ad-closeNN** [MFn233/PCL-Mainpage#10]
我已知晓作者学业繁忙，无法及时进行反馈。

------

**建议**：
1.添加 "你知道吗"，使用`Text={hint}`即可 ……

**Comment by MFn233** [comment]
注释中注明了，启动游戏时会显示“你知道吗”，所以我只添加了回声洞。
当然我也可以试试放一个新的卡片，专门放“你知道吗“和回声洞：）
