### ISSUE TITLE
[建议]移动新闻主页位置

### ISSUE THREAD

**Issue by MCSteve123** [MFn233/PCL-Mainpage#13]
我已知晓作者学业繁忙，无法及时进行反馈。

------

**建议**：
把新闻页的iconbutton改一改，现在的图标个人觉得适合做弹窗（底下关于作者的那个）
新闻页最好弄本书的图标

**实现方法**：
就这点，不知道

**Comment by Ad-closeNN** [comment]
```xaml
<local:MyButton Padding="13,10,13,10" ColorType="Red"
                    Text="打开 Minecraft News" EventType="打开帮助" EventData="https://news.bugjump.net/News.json"/>
	<StackPanel Margin="0,0,0,15"/>
```
个人感觉这样会好些...?
![image](https://github.com/MFn233/PCL-Mainpage/assets/103355026/8ffb54c4-783f-4ac6-86a9-1f44d6f35c08)

**Comment by MCSteve123** [comment]
这样会占用更大空间，本身也只是个友情链接（可以试试local:MyTextButton放边上？）
不过个人认为用iconbutton更好

**Comment by MCSteve123** [comment]
现在新闻主页上面的提示条可以耶
就是这个：📰

**Comment by Ad-closeNN** [comment]
> 现在新闻主页上面的提示条可以耶 就是这个：📰
那这刚好能用`local:MyTextButton`装饰

**Comment by Ad-closeNN** [comment]
不会调大小，会的话麻烦帮改改
```xaml
<local:MyTextButton VerticalAlignment="Bottom" HorizontalAlignment="Right" Text="📰"
                         ToolTip="Minecraft新闻(作者：最亮的信标)" EventData="https://news.bugjump.net/News.json" EventType="打开帮助"/>
```
直接交到pr吧

**Comment by MCSteve123** [comment]
不行嘿，我试了一下，MyTextButton不能调前景色（[#2510](https://github.com/Hex-Dragon/PCL2/issues/2510)）

**Comment by MCSteve123** [comment]
我写成了这样：
```xaml
<Grid>
               <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="5*" />
                    <ColumnDefinition Width="0.4*"/>
                    <ColumnDefinition Width="0.3*" />
                    <ColumnDefinition Width="0.5*" />
               </Grid.ColumnDefinitions>
               <local:MyTextButton Grid.Column="1" Text="📰" Height="21" Margin="0,5,0,0" Foreground="{DynamicResource ColorBrush3}"
                    ToolTip="Minecraft新闻(作者：最亮的信标)" EventData="https://news.bugjump.net/News.json"
                    EventType="打开帮助" VerticalAlignment="Bottom"/>
               <local:MyIconButton Grid.Column="2" LogoScale="1.2" Logo="M13.5,4A1.5,1.5 0 0,0 12,5.5A1.5,1.5 0 0,0 13.5,7A1.5,1.5 0 0,0 15,5.5A1.5,1.5 0 0,0 13.5,4M13.14,8.77C11.95,8.87 8.7,11.46 8.7,11.46C8.5,11.61 8.56,11.6 8.72,11.88C8.88,12.15 8.86,12.17 9.05,12.04C9.25,11.91 9.58,11.7 10.13,11.36C12.25,10 10.47,13.14 9.56,18.43C9.2,21.05 11.56,19.7 12.17,19.3C12.77,18.91 14.38,17.8 14.54,17.69C14.76,17.54 14.6,17.42 14.43,17.17C14.31,17 14.19,17.12 14.19,17.12C13.54,17.55 12.35,18.45 12.19,17.88C12,17.31 13.22,13.4 13.89,10.71C14,10.07 14.3,8.67 13.14,8.77Z"
                    Height="21" Margin="0,5,0,0" ToolTip="关于作者"
                    EventData="关于作者|我是MFn233，一个妄图写出完美代码的程序员，该主页目前由我独立完成，并在GitHub上开源。欢迎你前往仓库为我的项目提issue\n\n如果你真的很希望更多地了解我，欢迎访问我的网站: mfn233.github.io\n\n鸣谢：\nMCSteve123(GitHub)提供增加Minecraft相关网页捷径的建议\nJingHai-Lingyun(GitHub)提供修复建议与改进建议\nSIPC(sipc.ink)帮助将主页文件挂载于云服务器\n\n©MFn233 2023/7/22" EventType="弹出窗口" VerticalAlignment="Bottom"/>
               <local:MyIconButton Grid.Column="3" LogoScale="1.2" Logo="M256.455,8C322.724,8.119,382.892,34.233,427.314,76.685L463.029,40.97C478.149,25.851,504,36.559,504,57.941L504,192C504,205.255,493.255,216,480,216L345.941,216C324.559,216,313.851,190.149,328.97,175.029L370.72,133.279C339.856,104.38 299.919,88.372 257.49,88.006 165.092,87.208 87.207,161.983 88.0059999999999,257.448 88.764,348.009 162.184,424 256,424 297.127,424 335.997,409.322 366.629,382.444 371.372,378.283 378.535,378.536 382.997,382.997L422.659,422.659C427.531,427.531 427.29,435.474 422.177,440.092 378.202,479.813 319.926,504 256,504 119.034,504 8.001,392.967 8,256.002 7.999,119.193 119.646,7.755 256.455,8z"
                    Height="21" Margin="0,5,0,0"
                    ToolTip="点此刷新" EventType="刷新主页" VerticalAlignment="Bottom"/>
          </Grid>
```
但问题是local:MyTextButton不支持前景色，在鼠标扫过后会变成黑色，很丑

**Comment by MCSteve123** [comment]
要么干脆挪“Minecraft相关”里去？

**Comment by Ad-closeNN** [comment]
> 我写成了这样：
> 
> ```
> <Grid>
>                <Grid.ColumnDefinitions>
>                     <ColumnDefinition Width="5*" />
>                     <ColumnDefinition Width="0.4*"/>
>                     <ColumnDefinition Width="0.3*" />
>                     <ColumnDefinition Width="0.5*" />
>                </Grid.ColumnDefinitions>
>                <local:MyTextButton Grid.Column="1" Text="📰" Height="21" Margin="0,5,0,0" Foreground="{DynamicResource ColorBrush3}"
>                     ToolTip="Minecraft新闻(作者：最亮的信标)" EventData="https://news.bugjump.net/News.json"
>                     EventType="打开帮助" VerticalAlignment="Bottom"/>
>                <local:MyIconButton Grid.Column="2" LogoScale="1.2" Logo="M13.5,4A1.5,1.5 0 0,0 12,5.5A1.5,1.5 0 0,0 13.5,7A1.5,1.5 0 0,0 15,5.5A1.5,1.5 0 0,0 13.5,4M13.14,8.77C11.95,8.87 8.7,11.46 8.7,11.46C8.5,11.61 8.56,11.6 8.72,11.88C8.88,12.15 8.86,12.17 9.05,12.04C9.25,11.91 9.58,11.7 10.13,11.36C12.25,10 10.47,13.14 9.56,18.43C9.2,21.05 11.56,19.7 12.17,19.3C12.77,18.91 14.38,17.8 14.54,17.69C14.76,17.54 14.6,17.42 14.43,17.17C14.31,17 14.19,17.12 14.19,17.12C13.54,17.55 12.35,18.45 12.19,17.88C12,17.31 13.22,13.4 13.89,10.71C14,10.07 14.3,8.67 13.14,8.77Z"
>                     Height="21" Margin="0,5,0,0" ToolTip="关于作者"
>                     EventData="关于作者|我是MFn233，一个妄图写出完美代码的程序员，该主页目前由我独立完成，并在GitHub上开源。欢迎你前往仓库为我的项目提issue\n\n如果你真的很希望更多地了解我，欢迎访问我的网站: mfn233.github.io\n\n鸣谢：\nMCSteve123(GitHub)提供增加Minecraft相关网页捷径的建议\nJingHai-Lingyun(GitHub)提供修复建议与改进建议\nSIPC(sipc.ink)帮助将主页文件挂载于云服务器\n\n©MFn233 2023/7/22" EventType="弹出窗口" VerticalAlignment="Bottom"/>
>                <local:MyIconButton Grid.Column="3" LogoScale="1.2" Logo="M256.455,8C322.724,8.119,382.892,34.233,427.314,76.685L463.029,40.97C478.149,25.851,504,36.559,504,57.941L504,192C504,205.255,493.255,216,480,216L345.941,216C324.559,216,313.851,190.149,328.97,175.029L370.72,133.279C339.856,104.38 299.919,88.372 257.49,88.006 165.092,87.208 87.207,161.983 88.0059999999999,257.448 88.764,348.009 162.184,424 256,424 297.127,424 335.997,409.322 366.629,382.444 371.372,378.283 378.535,378.536 382.997,382.997L422.659,422.659C427.531,427.531 427.29,435.474 422.177,440.092 378.202,479.813 319.926,504 256,504 119.034,504 8.001,392.967 8,256.002 7.999,119.193 119.646,7.755 256.455,8z"
>                     Height="21" Margin="0,5,0,0"
>                     ToolTip="点此刷新" EventType="刷新主页" VerticalAlignment="Bottom"/>
>           </Grid>
> ```
> 
> 但问题是local:MyTextButton不支持前景色，在鼠标扫过后会变成黑色，很丑

好像有问题？这个可点击的范围变大了
`红色指针是当前鼠标的位置`
![image](https://github.com/MFn233/PCL-Mainpage/assets/103355026/70dc033e-4359-497f-b98f-cd0335cc9516)

**Comment by Ad-closeNN** [comment]
> 要么干脆挪“Minecraft相关”里去？

Minecraft这么大个卡片，塞这么小个按钮容易看不见，也不是很美观
`也可以选择放在上面, 测试的时候懒得放了`
![image](https://github.com/MFn233/PCL-Mainpage/assets/103355026/ee19e7bf-e2a9-4ed0-ae0e-9c93c5f5dd64)

**Comment by MCSteve123** [comment]
我的意思是做成列表卡片

**Comment by Ad-closeNN** [comment]
那你来做吧，最好能交个pr

**Comment by MCSteve123** [comment]
好
明天

**Comment by MCSteve123** [comment]
不对啊，你先把你那pr关了吧

**Comment by Ad-closeNN** [comment]
> 不对啊，你先把你那pr关了吧

行...吧...

**Comment by MCSteve123** [comment]
现在出现了一个问题，`https://news.bugjump.net/News.json`变404了！好像是信标那边的问题……

**Comment by MCSteve123** [comment]
现在出现了一个问题，`https://news.bugjump.net/News.json`变404了！好像是信标那边的问题……

**Comment by Ad-closeNN** [comment]
> 现在出现了一个问题，`https://news.bugjump.net/News.json`变404了！好像是信标那边的问题……

额，没事，先做着吧，去信标的issue提问题就行了

**Comment by Ad-closeNN** [comment]
![image](https://github.com/MFn233/PCL-Mainpage/assets/103355026/88667f3a-6749-4e3e-a306-2260ce008858)
某discord服务器...可信吗...

**Comment by MCSteve123** [comment]
由于PCL不允许用local:MyListItem打开网络帮助，所以打算把主页作为local:MyButton放到“杂项”里^

**Comment by MCSteve123** [comment]
> ![image](https://private-user-images.githubusercontent.com/103355026/306136963-ec04ae39-c5fe-4510-9591-81bf445d0705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDQ3NTEsIm5iZiI6MTcwODQwNDQ1MSwicGF0aCI6Ii8xMDMzNTUwMjYvMzA2MTM2OTYzLWVjMDRhZTM5LWM1ZmUtNDUxMC05NTkxLTgxYmY0NDVkMDcwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQwNDQ3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjNkOTMxZTEzYTA0MDQwMDBjMjQyZmUwNWQ1NWE2YjUwNzY0MmI2MWFlY2RkNDE4OGU5Mzc0NDVlMDNjZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R_ShOonlzoF1uVcliEyQLeIR3WJnsJJ1ivOBbU8Zzlc) 某discord服务器...可信吗...

大概率可信，请看VCR：https://t.bilibili.com/899749241434406921

**Comment by MCSteve123** [comment]
龙猫都这么说了

**Comment by Ad-closeNN** [comment]
![image](https://github.com/MFn233/PCL-Mainpage/assets/103355026/3bfbb6de-1bfa-4156-9035-ede4bce69422)

**Comment by Ad-closeNN** [comment]
HIDE一下吧去discussion

**Comment by MCSteve123** [comment]
咋又修好了？

**Comment by MCSteve123** [comment]
> 咋又修好了？

News.json又回来了？刚才不还没有吗？啊？

**Comment by MFn233** [comment]
现在访问信标的json文件，返回这个玩意：

>{"Title":"新闻主页主界面"}

**Comment by Ad-closeNN** [comment]
> 现在访问信标的json文件，返回这个玩意：
> 
> > {"Title":"新闻主页主界面"}

但是依然能用

**Comment by MFn233** [comment]
已经修改过了
