### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Rushbe2021** [MFn233/PCL-Mainpage#24]
**Bug描述**
在用了启动器工具中的内存优化功能后，任务管理器性能选项卡里拖动时会出现卡顿的现象，而且图标也被改成圆圈了（这个右键显示图形就能改回来）
也不知道是不是bug，还有这个内存优化什么原理...

**截图**
如果方便，请提供截图。
![QQ202458-21212](https://github.com/MFn233/PCL-Mainpage/assets/89636294/211ab4e2-2973-461e-bfff-429c970a6513)

**Comment by MFn233** [comment]
**暂时不清楚原理**

此内存优化是PCL2自带功能，主页里只起到快捷访问的作用

此bug请上报到PCL2仓库当中，或在PCL2仓库issue里查重，而不是来这里访问

（我可能要在启动器工具选项卡里加一个类似的提示）
