### ISSUE TITLE
一个问题（没有discussions只能在这里提了）

### ISSUE THREAD

**Issue by MCSteve123** [MFn233/PCL-Mainpage#3]
自己改进主页后能交pr吗？
~我知道作者学业繁忙，所以问一下，毕竟这样不用麻烦作者了，只要看看合不合适然后close或者marge就行……~

**Comment by MCSteve123** [comment]
回答了就close吧，谢谢

**Comment by JingHai-Lingyun** [comment]
你可以尝试下交 pr 看看会不会合并

**Comment by MCSteve123** [comment]
下次有想法了就交
~（自学XAML中）~

**Comment by JingHai-Lingyun** [comment]
@MFn233 去看PCL的2936帖 你主页加载问题

**Comment by JingHai-Lingyun** [comment]
呸 2963帖

**Comment by MFn233** [comment]
@JingHai-Lingyun 焯，怎么出来这么个事

**Comment by MFn233** [comment]
@JingHai-Lingyun b站搜MFn_，这里不太方便实时交流‘
还有我可能不会及时回复，见谅

**Comment by JingHai-Lingyun** [comment]
OK
