### ISSUE TITLE
[建议]Minecraft相关一栏建议增加REMCBBS

### ISSUE THREAD

**Issue by Cai-kunkun** [MFn233/PCL-Mainpage#30]
我已知晓作者学业繁忙，无法及时进行反馈。

------

**建议**：
1.在"Minecraft相关"一栏中加入"REMCBBS"（毕竟Mcbbs寄了）
……

**实现方法**：
<local:MyListItem Margin="-2,0,0,0" Logo="https://remcbbs.com/favicon.ico" Title="REMCBBS" Info="重建MCBBS!" EventType="打开网页" EventData="https://www.remcbbs.com" Type="Clickable" />

**效果展示**
![屏幕截图 2024-06-02 192726](https://github.com/MFn233/PCL-Mainpage/assets/126553009/c7bb03e9-bf54-4e4d-ac2b-ba8dc5d7ca53)

**Comment by MFn233** [comment]
好像和之前那个不是一家的吧

**Comment by MFn233** [comment]
还有一个，mcbbs.red
以及这上面其实不全，还有9minecraft,1mincraft,minecraftforum,minecraft-mods,minecraftxz

**Comment by MFn233** [comment]
我可能考虑单独开一个“国外mc网站”与“国内mc网站”

**Comment by MFn233** [comment]
mcpedl之外还有mcdlhub
除了以上之外还有cbergit

**Comment by Cai-kunkun** [comment]
额汗流浃背了

**Comment by MCSteve123** [comment]
有点太多了？~干脆整个Minecraft BBS Market算了~

**Comment by MFn233** [comment]
我加入了remcbbs制作组（

**Comment by MFn233** [comment]
>  有点太多了？~干脆整个Minecraft BBS Market算了~

你的馊主意，我把我知道的主流mc网站全加上了（
这些都是不那么主流的（吧

**Comment by MCSteve123** [comment]
> > 有点太多了？~干脆整个Minecraft BBS Market算了~
> 
> 你的馊主意，我把我知道的主流mc网站全加上了（ 这些都是不那么主流的（吧

我都没想过会有那么多网站（

**Comment by Cai-kunkun** [comment]
额

**Comment by Cai-kunkun** [comment]
666

**Comment by Cai-kunkun** [comment]
![image](https://github.com/MFn233/PCL-Mainpage/assets/126553009/917c32d2-adc4-44c1-ba0e-a017769693f7)
咳咳，Remcbbs极品id

**Comment by MFn233** [comment]
> ![image](https://github.com/MFn233/PCL-Mainpage/assets/126553009/917c32d2-adc4-44c1-ba0e-a017769693f7)
> 咳咳，Remcbbs极品id
> 

草

**Comment by MCSteve123** [comment]
这ID是你能取的吗（恼

**Comment by Cai-kunkun** [comment]
不止如此我还有很多极品id比如007,龙腾猫跃等等等等

**Comment by Ad-closeNN** [comment]
![image](https://github.com/user-attachments/assets/e1fae560-5c58-4f37-8bea-289f14b2b133)

**Comment by MFn233** [comment]
@Ad-closeNN 草
