### ISSUE TITLE
[建议]一些新TODO

### ISSUE THREAD

**Issue by MFn233** [MFn233/PCL-Mainpage#31]
1.删除整个网页捷径卡片改为网页捷径“区域”，不同类型的网站有不同分区，不做二级卡片（卡死人）
类似下面的效果：

——网页捷径——（不是一个卡片）
搜索框【                 】
        常用网站         V（卡片）
1.xxx
2.xxx
        MC相关           V（卡片）
1.xxx
2.xxx

2.MC相关，加入REMCBBS，加入MCArchive
REMCBBS：remcbbs.com
MCArchive：https://github.com/MCArchive/MCArchive

**Comment by MFn233** [comment]
除了我有谁能看懂（（

**Comment by MCSteve123** [comment]
看不懂（恼

**Comment by MCSteve123** [comment]
不对啊，没卡片怎么加元素？

**Comment by MCSteve123** [comment]
> 看不懂（恼

现在看懂了（

**Comment by MCSteve123** [comment]
![image](https://github.com/MFn233/PCL-Mainpage/assets/121204926/7747cdd7-1b5b-48f0-a4d3-493fe908d52c)
这做一半也是做嘛
