### ISSUE TITLE
我可能将增加一个分支版本，离线版

### ISSUE THREAD

**Issue by MFn233** [MFn233/PCL-Mainpage#35]
这个版本仅包含离线内容，方便离线PCL用户使用。
他将：把所有icon都替换为pcl pack://
并且删除许多离线不必要的内容

现在仍然在设想当中。。。

**Comment by FutureStudios-FSC** [comment]
据龙猫所说，PCL启动时都会本地缓存当前主页

**Comment by FutureStudios-FSC** [comment]
但是确实可以做一个

**Comment by MFn233** [comment]
会缓存，但是纯离线有的东西就没必要了
