### ISSUE TITLE
[BUG] Minecraft新闻选项出现错误

### ISSUE THREAD

**Issue by MoIei** [MFn233/PCL-Mainpage#37]
**Bug描述**
在网络正常的情况下点击“Minecraft新闻”会出现报错。具体如下图

**触发步骤**
详细阐述触发该bug所需步骤：
1. 来到 “更多” 目录；
2. 点击 ”Minecraft新闻“ 控件；
3. bug触发。
![725490d61fc47bb045be790038944d1](https://github.com/MFn233/PCL-Mainpage/assets/142684835/707eec23-10f2-45f6-bb9d-1e43900b38ce)

**Comment by MoIei** [comment]
注：仅能在科学上网的情况下进入，但是我感觉既然这样的话“Minecraft新闻”功能应当删除或隐藏，毕竟没人会为了看这个去科学上网

**Comment by MFn233** [comment]
这玩意难道被墙了？？

**Comment by MFn233** [comment]
找信标，别找我

**Comment by MFn233** [comment]
而且我可以用
![image](https://github.com/MFn233/PCL-Mainpage/assets/103323756/dd30aee0-e272-4baf-b406-7bd3d8dabf3b)

**Comment by MoIei** [comment]
我还是不行？？
算了那先关闭issue吧
