### ISSUE TITLE
[建议]另辟蹊径在PCL内启动已安装的基岩版的方法

### ISSUE THREAD

**Issue by erqianwu** [MFn233/PCL-Mainpage#40]
我已知晓作者学业繁忙，无法及时进行反馈。

------

**建议**：
### 首先说一下，是针对minecraft://暂时失效导致的，不是代替官方启动器用的。
进入正题。
PCL2预设主题“简单主页”中有一个可以启动本地Minecraft基岩版的功能，而这个功能现已失效。
或许可以使用启动文件的方法，先让用户自己创建一个基岩版Minecraft的快捷方式，再去启动它，代码大致如下：
`<local:MyButton Margin="0,4,0,8" Width="200" Height="35"
                    Text="启动Minecraft基岩版" EventType="打开文件" EventData="C:\Users\***\Desktop\minecraft" />`
经本人测试，可以正常使用，且效果很好，**不需要很大精力就可以修复**。

**实现方法**：
上面有

**Comment by MFn233** [comment]
那也很简单了，可以用cmd启动啊，
cmd start minecraft://

**Comment by MFn233** [comment]
测试了一下可以
你现在按win+r，输入：
> cmd /C "start minecraft:// \n exit"

**Comment by MFn233** [comment]
将在下个版本实装
