### ISSUE TITLE
Using URL Scheme to Launch MCBE

### ISSUE THREAD

**Issue by JingHai-Lingyun** [MFn233/PCL-Mainpage#43]
https://github.com/Hex-Dargon/PCL2#3985 has been fixed (by https://github.com/Hex-Dargon/PCL2#3999)
Now avaliable launch MCBE with using url scheme

**Comment by Ad-closeNN** [comment]
修一下链接

**Comment by MFn233** [comment]
暂时不改

**Comment by JingHai-Lingyun** [comment]
why not ~~~

**Comment by Ad-closeNN** [comment]
如果不改的话确实是能用不过就是会先弹出个黑框框才启动mc（电脑不行黑框框就停留得更久）

**Comment by MFn233** [comment]
黑框框没了
