### ISSUE TITLE
[BUG] 无法访问主页

### ISSUE THREAD

**Issue by RichardWang2127** [MFn233/PCL-Mainpage#5]
打开PCL2时报错无法加载
<img width="868" alt="image" src="https://github.com/MFn233/PCL-Mainpage/assets/150587741/73b378c7-ce9d-431c-a9d2-dff18e5de0f5">

**Comment by MFn233** [comment]
请去pcl discussion搜寻“简单主页”以获取解决方案

**Comment by RichardWang2127** [comment]
好的，已解决，谢谢
