### ISSUE TITLE
[BUG] 联网下载自定义主页失败

### ISSUE THREAD

**Issue by Cai-kunkun** [MFn233/PCL-Mainpage#51]
**Bug描述**
如标题

**触发步骤**
如标题

**修改建议**
bzd

**截图**
![image](https://github.com/user-attachments/assets/f70b570c-ecb4-4387-a2ef-c380ab3fc346)

**Comment by Ad-closeNN** [comment]
@Cai-kunkun 
https://github.com/Hex-Dragon/PCL2/discussions/5011

**Comment by wuliaodexiaoluo** [comment]
can be close as no planned(

**Comment by Cai-kunkun** [comment]
sure
