### ISSUE TITLE
[建议]找了个二次元图的API……

### ISSUE THREAD

**Issue by MCSteve123** [MFn233/PCL-Mainpage#9]
我已知晓作者学业繁忙，无法及时进行反馈。

------

**建议**：
`https://api.likepoems.com/img/pc`

**实现方法**：
```xaml
<local:MyButton Grid.Column="1" Margin="0,0,0,0" Height="35" Text="二次元图" EventType="打开网页" EventData="https://api.likepoems.com/img/pc"/>
```

---
另：我可能还会发个pr，不过是小改动，大概就是格式化代码、整理逻辑一类的，您测一下API，没问题顺带写上（主要是太闲了，想往lm那边看看又不会vb……）
![image](https://github.com/MFn233/PCL-Mainpage/assets/121204926/151814f8-9fa7-4826-b29f-f8c9fb12b9b3)
~一坨红色的不规范缩进~

**Comment by MCSteve123** [comment]
测了30多张图，没r18

**Comment by MCSteve123** [comment]
我收回那句话……

**Comment by MFn233** [comment]
hhhc
